### ISSUE TITLE
Block while waiting for connection handshake from server

### ISSUE THREAD

**Issue by henvic** [wedeploy/gosocketio#4]
https://github.com/henvic/socketio/blob/2dd4801214147d0cb62f46d48c057f39e0bcf536/client.go#L396-L400

handles the connection handshake, but there is nothing blocking messages from being sent before the connection is established. This means that the server might not be ready to handle a message when it receives it due to concurrency issues.

**Comment by anitaderiane** [comment]
Hi @henvic, can you please prioritize the bug according to the [prioritization system](https://docs.google.com/presentation/d/1rFR7fANMO7bFCc1UG2RXOIGoF8BXTs6AGZC4SsZhPuI/edit#slide=id.p)?

**Comment by henvic** [comment]
Closed with db91a301d0eec9adc4e727ea31dc221def05952a.
